
colorscheme molokai

set guifont=Menlo\ Regular\ for\ Powerline:h13

set linespace=1
set antialias

" Don't beep
set visualbell

" No toolbar, No scrollbars
set go-=T
set go-=l
set go-=L
set go-=r
set go-=R

